# ***TP7*** <br> 
### *préparé par :* <br>
##### - Agbalou Mohamed Reda
##### - Mariem Dargal
##### - Basma Charid

# EXERCICE  1:
Soit la matrice A suivante :

<p style="font-family: consolas, serif; font-size:11pt; font-style:italic">
     

\\    $A=\left(\begin{array}{llll}4 & 4 & 2 & 0 \\ 4 & 5 & 0 & 0 \\ 2 & 0 & 6 & 1 \\ 0 & 0 & 1 & 2\end{array}\right)$ 


</p>

<p style="font-family: consolas, serif; font-size:12pt; font-style:italic">
    1- Resoudre AX=b(Pour b &sub; R**4 choisi) par la methode de cholesky et housholder et jacobi . COMPARER
    <br>
</p>

<p style="font-family: consolas, serif; font-size:12pt; font-style:italic">
    2- Resoudre AX=b par la methode du gradient à pas optimal . COMPARER
    <br>
</p>

<p style="font-family: consolas, serif; font-size:12pt; font-style:italic">
    3- Calculer les valeurs propres de A par la methode de Givens-householder
    <br>
</p>

## **Méthode de résolution d'un système linéaire Ax=B**

### 1  ***Méthode de cholesky***

c'est une méthode directe
>  Il faut s'assurer que la matrice est symétrique définie positive tout d'abord
La première étape consiste à trouver la matrice L de A par cette fonction cholesky() pour en déduire la décomposition de A qui la multiplication de L avec L transposé.

La première étape consiste à trouver la matrice L de A par cette fonction cholesky() pour en déduire la décomposition de A qui la multiplication de L avec L transposé.

In [130]:
import numpy as np
def cholesky(a):
    a=np.array(a,float)
    L=np.zeros_like(a)      #cree matrice de meme ordre que a
    n,_=np.shape(a)     #ordre du matrice carree prenons premier ligne car 2
    for i in range(n):
        for j in range(i,n):
            if j==i:
                L[j,i]=np.sqrt(a[j,i]-np.sum(L[j,:i]**2))    #cours
            else:
                L[j,i]=(a[j,i]-np.sum(L[j,:i]*L[i,:i]))/L[i,i]
    return L
A=[[4, 4, 2, 0], [4, 5, 0, 0], [2, 0, 6, 1], [0, 0, 1, 2]]
b=[1, 0, 1, 0]
L=cholesky(A)
print(L)


[[ 2.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 1. -2.  1.  0.]
 [ 0.  0.  1.  1.]]


> La deuxième étape consiste à résoudre le système linéaire Ax=b par la résolution de Ly=b puis L^t x=y

In [131]:
def solveLU(L,U,b):
    L=np.array(L,float)
    U=np.array(U,float)
    b=np.array(b,float)
    n,_=np.shape(L)
    y=np.zeros(n)
    x=np.zeros(n)
    #forward substitution
    for i in range (n):
        sumj=0
        for j in range (i):
            sumj+=L[i,j]*y[j]
        y[i]=(b[i]-sumj)/L[i,i]
    #backward substitution
    for i in range (n-1,-1,-1):
        sumj=0
        for j in range (i+1,n):
            sumj+=U[i,j]*x[j]
        x[i]=(y[i]-sumj)/U[i,i]
    return x
X=solveLU(L,np.transpose(L),b)
print(f"la solution de ce système par la méthode de cholesky est : {X}")

la solution de ce système par la méthode de cholesky est : [ 8.75 -7.   -3.    1.5 ]


### 2 ***Méthode du Householder :***

<p style="font-family: consolas, serif; font-size:14pt; font-style:italic">
    La méthode de Householder est une technique de résolution de systèmes linéaires qui permet de trouver la solution d'un système du type Ax = b, où A est une matrice n x n et b est un vecteur n x 1. Elle est particulièrement utile lorsque la matrice A est symétrique ou de haute conditionnement<br>
    Q : unitaire (orthogonale Q**-1 = Q**t)<br>
    R : une matrice triangulaire supérieure avec r<sub>ii</sub> > 0
    <br>
</p>

<p style="font-family: consolas, serif; font-size:12pt; font-style:italic">
    Principle : <br>
        $\left\{\begin{array}{l}A x=B \\ A=QR\end{array} \Rightarrow Q \cdot R*x = B \Rightarrow\left\{\begin{array}{l}Q y=B \\ R x=y\end{array}\right.\right.$
    <br>
</p>

<p style="font-family: consolas, serif; font-size:11pt; font-style:italic">
    on calcule la matrice de Householder associé a v:
</p>

<p style="font-family: consolas, serif; font-size:11pt; font-style:italic">
    on a :<br>
    $\left.\begin{array}{rl}v_{k}= & \frac{a_{k}}{\left\|a_{k}\right\|}-e_{1} \\ u_{k}= & \frac{v_{k}}{\left\|v_{k}\right\|}\end{array}\right\} \Rightarrow u_{k}=\frac{a_{k}-\left\|a_{k}\right\| e_{1}}{\left\|a_{k}-\right\| a_{k}\left\|e_{1}\right\|}$
</p>

In [132]:
A = array([[4, 4, 2, 0], [4, 5, 0, 0], [2, 0, 6, 1], [0, 0, 1, 2]])
B = [1, -1, 0, 1]

In [133]:
def HS(mat):
    """
    mat: this is the given matrix
    n: the matrix size
    Id: the identity matrix of size n
    e1: first canonical basis vector
    u: a vector obtained by the above method
    H: this is the Hous-Holder matrix
    HA: the H*A product
    """
    n = len(mat)
    Id = eye(n)

    e1 = array([Id[:, 0]])
    a = array([mat[:, 0]])
    v = a - linalg.norm(a, 2) * e1
    u = v / linalg.norm(v, 2)

    H = eye(n) - 2 * transpose(u).dot(u)
    HA = H.dot(mat)

    return H, HA

<p style="font-family: consolas, serif; font-size:11pt; font-style:italic">
    *** Puis la Decomposition QR :
</p>

<p style="font-family: consolas, serif; font-size:11pt; font-style:italic">
   on a : <br>
         $A=Q R$ tel que
$Q \in M_{n \times n}(R)$ orthogonal and $R \in M_{n \times n}(R)$ triangulaire superieur. <br>
     $R=H_{n-1} H_{n-2} \cdots H_{1} A$&nbsp;&nbsp;&nbsp;et&nbsp;&nbsp;&nbsp;$Q=\left(H_{n-1} H_{n-2} \cdots H_{1}\right)^{-1}$
</p>

In [134]:
def QR_decomp(A):
    """
    A: the given matrix
    Hmax: list to store Hous-Holder matrices
    HAmax: list to store the H*A matrices
    M: is a temporary Matrix
    @: operator for the matrix product
    R: the QR decomposition matrix R (return value)
    Q: the QR decomposition matrix Q (rerun value)
    """
    n = len(A)
    Hmax = []
    HAmax = []

    H1, HA1 = HS(A)
    M = HA1[1:, 1:]
    Hmax.append(H1)
    HAmax.append(HA1)
    
    for i in range(1, n - 1):
        H, HA = HS(M)
        HAmax.append(HA)
        M = HA[1:, 1:]
        k = i
        while k > 0:
            H = Add_Id(H)
            k -= 1
        Hmax.append(H)

    R = eye(n)
    for i in range(n - 1):
        R = Hmax[i] @ R

    Q = transpose(R)
    R = R.dot(A)

    return Q, R

<p style="font-family: consolas, serif; font-size:14pt; font-style:italic">
    D'ou la solution du system A*X = B en utilisant la method QR
    <br>
</p>

<p style="font-family: consolas, serif; font-size:12pt; font-style:italic">
    <br>
        $\left\{\begin{array}{l}A x=B \\ A=QR\end{array} \Rightarrow Q \cdot R*x = B \Rightarrow\left\{\begin{array}{l}Q y=B \\ R x=y\end{array}\right.\right.$
    <br>
</p>

In [135]:
Q, R = QR_decomp(A)
Y = linalg.solve(Q, B)
X = linalg.solve(R, Y)
print("\nLa solution de AX=b avec la methode de Householder donne :\n")
print("X = ", X)


La solution de AX=b avec la methode de Householder donne :

X =  [ 27.25 -22.   -10.     5.5 ]


### 3 ***Méthode de Jacobi :***

<p style="font-family: consolas, serif; font-size:14pt; font-style:italic">
La méthode de Jacobi est une méthode itérative pour résoudre un système linéaire Ax = b. Elle consiste à itérer sur chaque équation du système et à mettre à jour la valeur de chaque inconnue en fonction des autres inconnues déjà connues.
<p>

In [136]:
import numpy as np

def Jacobi(A, b, x0, tol, maxiter):
    """
    Solve a system of linear equations Ax = b using the Jacobi method.

    Parameters:
    - A: coefficient matrix (n x n)
    - b: right-hand side vector (n x 1)
    - x0: initial guess for the solution (n x 1)
    - tol: tolerance for the residual (scalar)
    - maxiter: maximum number of iterations (scalar)

    Returns:
    - x: the solution vector (n x 1)
    - iterations: the number of iterations performed (scalar)
    - res: the final residual (scalar)
    """

    # Get the dimensions of the matrix
    n = A.shape[0]

    # Initialize the iteration counter
    iterations = 0

    # Compute the initial residual
    res = np.linalg.norm(b - np.matmul(A, x0))

    # Initialize the solution vector
    x = x0

    # Start the iteration loop
    while iterations < maxiter and res > tol:
        # Increment the iteration counter
        iterations += 1

        # Loop over the rows of the matrix
        for i in range(n):
            # Compute the new value for the i-th component of the solution vector
            x[i] = (b[i] - np.dot(A[i, :i], x[:i]) - np.dot(A[i, i + 1:], x[i + 1:])) / A[i, i]

        # Compute the new residual
        res = np.linalg.norm(b - np.matmul(A, x))

    # Return the solution vector, the number of iterations performed, and the final residual
    return x, iterations, res

A = np.array([[4, 4, 2, 0], [4, 5, 0, 0], [2, 0, 6, 1], [0, 0, 1, 2]
])
b = np.array([1, 0, 1, 0])
x0 = np.zeros(4)  # initial guess for the solution
tol = 1e-6  # tolerance for the residual
maxiter = 100  # maximum number of iterations

x, iterations, res = Jacobi(A, b, x0, tol, maxiter)

print(x)
print(iterations)
print(res)

[ 7.32656522 -5.86125217 -2.48152924  1.24076462]
100
0.10191564372952595


### 4 ***Méthode de gradient à pas optimal   :***

<p style="font-family: consolas, serif; font-size:14pt; font-style:italic">
    Resoudre AX=b par la methode du gradient à pas optimal 
    <br>
</p>

<p style="font-family: consolas, serif; font-size:12pt; font-style:italic">
    Principle : <br>
        We consider the following problem: minimize on $R^{n}$ the function $\phi$ defined by
    $$
    \phi(x)=\frac{1}{2} x^{T} A x-b^{T} x
    $$
</p>

<p style="font-family: consolas, serif; font-size:12pt; font-style:italic">  On a A est une matrice symetrique definie positive.
    The interest of the question comes from the fact that the minimum of $\phi$ is reached for $x^{*}=A^{-1} b$, and this solution is unique. Indeed, the gradient of $\phi$ in $x=\left(x_{1} \ldots x_{n}\right)^{T} \in R^{n}$ is the vector:
</p>

<p style="font-family: consolas, serif; font-size:12pt; font-style:italic">
    $$
    \nabla \phi(x)=\left(\frac{\partial \phi}{\partial x_{1}} \frac{\partial \phi}{\partial x_{2}} \cdots \frac{\partial \phi}{\partial x_{n}}\right)^{T}=\frac{1}{2} A x+\frac{1}{2} A^{T} x-b=A x-b
    $$
</p>

<p style="font-family: consolas, serif; font-size:12pt; font-style:italic">
    which vanishes only for $x^{*}=A^{-1} b$. Note that in this calculation we have used the fact that $A$ is a symmetric matrix. The vector $x^{*}=A^{-1} b$ is therefore the unique critical point of $\phi$ and, since $A$ is positive definite, it is a global minimum.
    <br>
</p>

<p style="font-family: consolas, serif; font-size:14pt; font-style:italic">
    To calculate $x^{(k+1)}$ from $x^{(k)}$, we then minimize the function $\phi$ on the direction vector line $p^{(k)}$ and going through $x^{(k)}$: we therefore choose
    $$
    x^{(k+1)}=x^{(k)}+\alpha_{k} p^{(k)}
    $$
    where $\alpha_{k} \in R$
    <br>
</p>

<p style="font-family: consolas, serif; font-size:14pt; font-style:italic">
    To calculate $x^{(k+1)}$ from $x^{(k)}$, we then minimize the function $\phi$ on the direction vector line $p^{(k)}$ and going through $x^{(k)}$: we therefore choose
    $$
    x^{(k+1)}=x^{(k)}+\alpha_{k} p^{(k)}
    $$
    where $\alpha_{k} \in R$
    <br>
</p>

<p style="font-family: consolas, serif; font-size:12pt; font-style:italic">
    definition of the function $\phi(x)$ and $\nabla \phi(x)$
    <br>
</p>

In [137]:
def phi(A, b, x):
    return 0.5 * np.dot(np.dot(np.transpose(x), A), x) - np.dot(np.transpose(b), x)


In [138]:
def Dphi(A, b, x):
    return np.dot(A, x) - b

In [139]:
A = np.array([[4, 4, 2, 0], [4, 5, 0, 0], [2, 0, 6, 1], [0, 0, 1, 2]])
B = np.array([1, -1, 0, 1])
n = len(A)
Alpha = 0.01  # step
epsilon = 1e-9  # convergence tolerance
max_iters = 1e6  # maximum iterations

x0 = np.array([1, 0, 0, 1])

In [140]:
# Gradient method function
def gradient_methode(A, b, x0):
    # initialization of the starting vector
    next_x = x0
    # Display initial vector
    print("i = 0 ; phi(x)= " + str(phi(A, b, next_x)))
    i = 1
    # convergence flag
    cvg = False
    print("Search start")
    while i <= max_iters:
        curr_x = next_x
        next_x = curr_x - Alpha * Dphi(
            A, b, curr_x
        )  # formula of X(k+1) under the gradient method

        diff = next_x - curr_x
        # convergence test
        if (
            np.linalg.norm(diff, 2) / (np.linalg.norm(next_x, 2) + np.finfo(float).eps)
            <= epsilon
        ):
            cvg = True
            break
        # display the Approximate value of phi(x) during the search for the minimum
        print("i = " + str(i) + " ; phi(x)= " + str(phi(A, b, next_x)))
        i += 1

    # if we have convergence we display the solution as result if not we display a message
    # that the sequence is divergent
    if cvg:
        print("The Min obtained in " + str(i) + " iterations.")
        print("x_sol =", next_x)
    else:
        print("the sequence isn't converge.")

    return next_x

In [141]:
x_sol = gradient_methode(A, B, x0)

i = 0 ; phi(x)= 1.0
Search start
i = 1 ; phi(x)= 0.5789499999999999
i = 2 ; phi(x)= 0.22693259500000007
i = 3 ; phi(x)= -0.06808693968450008
i = 4 ; phi(x)= -0.31603985840323734
i = 5 ; phi(x)= -0.5251217748971575
i = 6 ; phi(x)= -0.7020961639495771
i = 7 ; phi(x)= -0.8525447852397126
i = 8 ; phi(x)= -0.9810743121168872
i = 9 ; phi(x)= -1.0914868245611276
i = 10 ; phi(x)= -1.1869204860688838
i = 11 ; phi(x)= -1.269965618945377
i = 12 ; phi(x)= -1.3427604805262767
i = 13 ; phi(x)= -1.4070702903849737
i = 14 ; phi(x)= -1.4643524377141213
i = 15 ; phi(x)= -1.515810285785956
i = 16 ; phi(x)= -1.562437567705091
i = 17 ; phi(x)= -1.6050550189010073
i = 18 ; phi(x)= -1.6443406040366666
i = 19 ; phi(x)= -1.6808544585671303
i = 20 ; phi(x)= -1.7150594692657144
i = 21 ; phi(x)= -1.7473382563826854
i = 22 ; phi(x)= -1.7780071867203162
i = 23 ; phi(x)= -1.80732793685391
i = 24 ; phi(x)= -1.8355170349215504
i = 25 ; phi(x)= -1.8627537344796379
i = 26 ; phi(x)= -1.889186512099299
i = 27 ; phi(x)= -1

In [142]:
print("The solution by the gradient method:")
print("X =  ",x_sol)

The solution by the gradient method:
X =   [ 27.249932   -21.99994516  -9.99997504   5.49998727]


In [143]:
print("la solution avec la methode classic")
x_sol2 = np.linalg.solve(A, B)
print(x_sol2)

la solution avec la methode classic
[ 27.25 -22.   -10.     5.5 ]


### 5 ***Calcule des valeurs propre par la methode de Givens   :***

La méthode de Givens est une techniques utilisée pour factoriser une matrice en produit de matrices triangulaires et orthogonales. 

In [144]:
import numpy as np

# Matrice A
A = np.array([[4, 4, 2, 0], [4, 5, 0, 0], [2, 0, 6, 1], [0, 0, 1, 2]])

# Fonction de rotation de Givens
def givens_rotation(a, b):
  if b == 0:
    c = 1
    s = 0
  else:
    if abs(b) > abs(a):
      tau = -a / b
      s = 1 / np.sqrt(1 + tau**2)
      c = s * tau
    else:
      tau = -b / a
      c = 1 / np.sqrt(1 + tau**2)
      s = c * tau
  return c, s

# Méthode de Givens-Householder
def givens_householder(A):
  m, n = A.shape
  Q = np.eye(m)
  R = A.copy()
  for j in range(n):
    for i in range(m-1, j, -1):
      c, s = givens_rotation(R[i-1, j], R[i, j])
      G = np.eye(m)
      G[i-1, i-1] = c
      G[i, i] = c
      G[i-1, i] = s
      G[i, i-1] = -s
      R = G.dot(R)
      Q = Q.dot(G.T)
  return Q, R

# Calcul des valeurs propres
Q, R = givens_householder(A)
vals, vecs = np.linalg.eig(R)

# Valeurs propres triées
vals = np.sort(vals)

print(vals)


[0.06595462+0.j         1.82621444+0.j         5.56386936-1.50096944j
 5.56386936+1.50096944j]


# EXERCICE  2:

<p style="font-family: consolas, serif; font-size:11pt; font-style:italic">
    La méthode de Newton est une méthode itérative pour résoudre des équations non linéaires.La méthode de Newton est souvent utilisée pour trouver les racines d'une fonction, c'est-à-dire les points où la fonction s'annule.
    Dans l'exercice suivant on va resoudre le Systeme suivant avec la methode de Newton <br>
    the system concerned is as follows:<br>
$$
\left\{
    \begin{array}\\
        x^{2}-y = 0 \\
        \               &avec (x_0,y_0)=(1,1) \\
        y^{2}=0 \\
    \end{array}
\right.
$$
</p>


définition des fonctions du système


In [145]:
def f1(x, y):
    return x ** 2 - y


def f2(x, y):
    return y ** 2

définition de la jacobienne


In [146]:
def jacobian(x, y):
    return np.array([[2 * x, -1], [0, 2 * y]])

In [147]:
# définition de la méthode de Newton
def newton_method(x0, y0, epsilon=1e-7, max_iter=100):
    # initialisation des variables
    x = x0
    y = y0
    converged = False
    iter = 0

    # boucle jusqu'à convergence ou nombre maximal d'itérations atteint
    while not converged and iter < max_iter:
        # calcul de la jacobienne en (x, y)
        J = jacobian(x, y)
        # calcul de l'inverse de la jacobienne
        Jinv = np.linalg.inv(J)
        # calcul de F(x, y) et F(x0, y0)
        F = np.array([f1(x, y), f2(x, y)])
        F0 = np.array([f1(x0, y0), f2(x0, y0)])
        # calcul de la différence entre F(x, y) et F(x0, y0)
        deltaF = F - F0
        # calcul de la différence entre (x, y) et (x0, y0)
        delta = Jinv.dot(deltaF)
        # mise à jour des estimations de x et y
        x = x0 + delta[0]
        y = y0 + delta[1]
        # vérification de la convergence
        if np.abs(delta).max() < epsilon:
            converged = True
        # incrémentation du compteur d'itérations
        iter += 1

    # retourne la solution trouvée et le nombre d'itérations
    return (x, y), iter


# test de la méthode en utilisant (x0, y0) = (1, 1) comme point de départ
solution, nb_iter = newton_method(1, 1)
print("Solution trouvée:", solution)
print("Nombre d'itérations:", nb_iter)


Solution trouvée: (1.0, 1.0)
Nombre d'itérations: 1
